server:
  port: 8080

spring:
  application:
    name: springboot17demo
  
  # 开发工具配置
  # 这是Spring Boot的开发工具（DevTools）配置部分。
  # 它启用了热重启功能（enabled: true），指定了需要监视的额外路径为src/main/java（当这个目录下的文件发生变化时会触发重启），
  # 同时排除了static目录下的文件（这些静态资源的变化不会触发应用重启）。
  # 这些配置可以提高开发效率，让你在开发过程中修改代码后不需要手动重启应用。
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**

# 日志配置
logging:
  level:
    root: info
    com.example.springboot17demo: debug